### ISSUE TITLE
Can't login to Portal Binusmaya

### ISSUE THREAD

**Issue by DerrellH** [chrsep/Kingfish#17]
Everytime i tried to logged in, it always says that the binusmaya server is acting weird while the others managed to login pls fix it my phone is Samsung J7 prime if it helps

**Comment by DerrellH** [comment]
Sorry typo there *Can't

**Comment by mstephen77** [comment]
I suspect there's some new features available only to newer Android version and that's why login keeps failing. Are you on Alpha channel? Please check #16 for login issues.

**Comment by chrsep** [comment]
Hi @DerrellH, can you tell us more? Are you Binusian 2021? There doesn't seem to be any Binusian 2021 who have successfully logged in to Portal. It's possible that your failed login is caused by Binusmaya server not telling Portal what Semester you are on. I've posted more info in #16.

**Comment by DerrellH** [comment]
Yes i am from Binusian 2021, one of the people sitting beside me managed to login to the portal binusmaya, i don't know how

**Comment by DerrellH** [comment]
And in my portal there is no verification tab, only a simple log in and password tab

**Comment by DerrellH** [comment]
And do i need to join the alpha tester so that i can logged in to the portal?

**Comment by mstephen77** [comment]
I don't know whether @chrsep has pushed it out for public or still for alpha testers, but yeah, please do try joining alpha testers.

**Comment by chrsep** [comment]
I have pushed it to public actually. Sorry, i forgot to mention that. @DerrellH There is a chance that you might be able to login in a few days, just need to wait until Binusmaya says you are on your first Semester. But yeah , you should still join the alpha testing if you want to get the updates as fast as possible, I'll try to fix this and if I am successful, I'll push it to the alpha testing first.

Btw, @DerrellH What do you mean by verification tab? are you referring to the captcha pop-ups that shows when trying to login? Does that one person who successfully logged in to Portal able to see his/her class schedule?

**Comment by DerrellH** [comment]
@Chrsep yes i think, and yeah i mean the Chaptcha pop-ups, idk it's just the person besides the dates of stuff i think on his app, maybe i'm just seeing things. If it's true that i can only start it until the first semester starts then okay, thx for the information

**Comment by mstephen77** [comment]
@DerrellH Newest binusmaya shouldn't have captcha popup, so I doubt your friend logged in successfully because the login system has been changed since the captcha update.

**Comment by DerrellH** [comment]
@mrstephen77 i still can't login to portal, the date for AO is out and yet it still says server acring wierd

**Comment by chrsep** [comment]
@DerrellH I am currently working on a fix, hopefully i can release an update before Monday. I'll be releasing this first on Alpha channel as soon as i can, probably with quite some bug though.

You can join the alpha channel from [here](https://play.google.com/apps/testing/com.directdev.portal) if you want to test the update as soon as possible.

**Comment by mstephen77** [comment]
@chrsep sorry can't be of much help, I've tried to build it and everything's fine for me.

**Comment by chrsep** [comment]
@mstephen77 don't worry, i can't be of much help either :rofl:. I've decided to just rewrite most of Portal and remove all data request from login, it will all be done later on after login.

The problem won't be gone though, it'll just be moved away from when the user tries to login, at least for now. 

I'll try gathering logs of recent requests leading to the failed request to Binusmaya using crashlytics, any sensitive info(cookies, password, etc) won't be logged though. I don't see any other way to find a fix for this.

**Comment by chrsep** [comment]
@DerrellH update is now being rolled out to alpha.

**Comment by chrsep** [comment]
@DerrelH Can you now login to Portal? is there still any error?

**Comment by purenaturalism** [comment]
Hi @chrsep , I'm binusian 2021. I can logged in now. Thanks!

Btw, How to contribute this project ? or What's the prerequisites to contribute to this project ? 

Thanks

**Comment by chrsep** [comment]
Hi @purenaturalism That's good to hear, does any error message still shows though? To contribute just [fork](https://guides.github.com/activities/forking/) this repo, make changes, and then make a pull-request. There is no prerequisite, just be clear on what does your changes do when you make your pull-request.
